# Academic Research Configuration for Social Scientists
# ==================================================
# Simplified configuration optimized for academic research into
# authoritarianism and violence in Brazilian society
#
# Week 1-2 Optimizations Integrated:
# - Emergency embeddings cache (40% cost reduction)
# - Smart semantic caching for Portuguese analysis
# - Academic budget controls
# - Research-focused defaults

# Academic Research Settings
academic:
  enabled: true                    # Enable academic optimizations
  monthly_budget: 50.0            # Conservative academic budget ($50/month)
  research_focus: "brazilian_politics"
  portuguese_optimization: true   # Optimize for Portuguese text
  cache_optimization: true        # Enable Week 1-2 cache optimizations
  
  # Research categories for Brazilian political analysis
  political_categories:
    - "direita"
    - "esquerda" 
    - "centro"
    - "bolsonarismo"
    - "petismo"
    - "neutro"

# Anthropic API Configuration (Academic-focused)
anthropic:
  enable_api_integration: true
  api_key: "${ANTHROPIC_API_KEY}"
  model: "claude-3-5-haiku-20241022"  # Most cost-effective for academic use
  rate_limit: 20                      # Conservative rate limiting
  max_tokens: 1000                    # Balanced output length
  temperature: 0.3                    # Consistent results for research
  
  # Academic fallback strategy
  fallback_models:
    - "claude-3-5-haiku-20241022"     # Primary (cheapest)

# Week 1: Emergency Cache Settings (Academic)
emergency_cache:
  enabled: true
  cache_dir: "cache/academic_embeddings"
  ttl_hours: 48                      # 2 days cache for research consistency
  max_memory_mb: 256                 # Conservative memory usage
  
# Week 2: Smart Cache Settings (Academic)
smart_cache:
  enabled: true
  cache_dir: "cache/academic_claude"
  ttl_hours: 72                      # 3 days for research reproducibility
  semantic_similarity_threshold: 0.85
  portuguese_normalization: true    # Normalize Brazilian political terms
  
# Voyage.ai Embeddings (Academic Optimized)
voyage_embeddings:
  model: "voyage-3.5-lite"          # Most economical option
  cache_enabled: true
  batch_size: 128
  sampling_rate: 0.04               # 96% sampling for cost control
  input_type: "document"
  
# Pipeline Settings (Research-focused)
pipeline:
  stages_enabled:
    - "01_chunk_processing"
    - "02_encoding_validation"
    - "03_deduplication"
    - "04_feature_validation"
    - "05_political_analysis"        # Key for political research
    - "06_text_cleaning"
    - "07_linguistic_processing"     # Portuguese language processing
    - "08_sentiment_analysis"        # Academic sentiment analysis
    - "09_topic_modeling"           # Research topic identification
    - "10_tfidf_extraction"         # Academic text analysis
    - "11_clustering"               # Data grouping for research
    - "19_semantic_search"          # Research query capabilities
    - "20_pipeline_validation"
  
  # Academic data handling
  chunk_size: 1000                  # Reasonable chunk size
  deduplication_enabled: true
  political_analysis_depth: "full"
  
# Logging (Academic-friendly)
logging:
  level: "INFO"
  academic_metrics: true
  cost_tracking: true
  cache_performance: true
  
# Output Settings (Research)
output:
  format: "csv"
  include_metadata: true
  preserve_original_text: true      # Important for research integrity
  academic_headers: true
  
# Budget Alerts (Academic-focused)
budget_alerts:
  monthly_threshold: 0.8            # Alert at 80% of budget
  weekly_threshold: 0.2             # Alert at 20% weekly usage
  enable_auto_downgrade: true       # Auto-switch to cheaper models
  
# Research Quality Settings
research_quality:
  reproducibility: true             # Ensure reproducible results
  data_integrity_checks: true
  bias_monitoring: true             # Monitor for analytical bias
  validation_sampling: 0.1          # 10% validation sample

# Performance Settings (Academic Computing)
performance:
  max_workers: 4                    # Conservative parallelization
  memory_limit_gb: 4.0              # Academic computing limit
  timeout_minutes: 30               # Reasonable timeout for research
  
# Portuguese Language Optimization
portuguese:
  enabled: true
  political_entity_recognition: true
  brazilian_variants: true
  social_media_normalization: true