# API Limits Configuration - TASK-023 v5.0.0
# Consolidates hardcoded API limits and thresholds from various modules
# Centralizes all API-related configuration for better maintainability

api_limits:
  # Anthropic API Configuration
  anthropic:
    # Model settings
    default_model: "claude-3-5-sonnet-20241022"
    fallback_model: "claude-3-5-haiku-20241022"
    
    # Token limits
    max_tokens: 4000
    max_input_tokens: 180000  # Claude Haiku limit
    max_message_tokens: 800   # Per message limit
    
    # Processing settings
    batch_size: 100
    temperature: 0.1
    confidence_threshold: 0.7
    
    # Rate limiting
    requests_per_minute: 50
    tokens_per_minute: 40000
    
    # Quality thresholds
    min_response_length: 10
    max_response_length: 4000
    
  # Voyage AI Configuration  
  voyage:
    # Model settings
    default_model: "voyage-3.5-lite"
    fallback_model: "voyage-3.5-lite"
    
    # Processing limits
    batch_size: 128
    max_tokens: 32000
    similarity_threshold: 0.75
    max_messages_per_dataset: 50000
    
    # Rate limiting
    requests_per_minute: 300
    embeddings_per_minute: 1000000
    
    # Quality settings
    min_similarity: 0.1
    max_similarity: 1.0
    
  # General processing thresholds
  processing:
    success_threshold: 0.7
    quality_threshold: 0.8
    min_batch_size: 10
    max_batch_size: 1000
    
    # Error handling
    max_retries: 3
    retry_delay: 1.0
    exponential_backoff: true
    
  # Cache configuration
  cache:
    embeddings_limit: 10000
    response_limit: 5000
    ttl_seconds: 3600
    enable_persistence: true
    
    # Cache thresholds
    memory_limit_mb: 512
    disk_limit_mb: 2048
    cleanup_threshold: 0.9