# =============================================================================
# CORE CONFIGURATION - Monitor do Discurso Digital v5.0.0  
# =============================================================================
# Configurações essenciais consolidadas (substitui parte do master.yaml)

# =============================================================================
# MODELOS E APIs - CONFIGURAÇÃO UNIFICADA
# =============================================================================
models:
  # Anthropic Configuration
  anthropic:
    # Modelos disponíveis
    available_models:
      primary: "claude-3-5-sonnet-20241022"
      enhanced: "claude-sonnet-4-20250514"
      fast: "claude-3-5-haiku-20241022"
    
    # Configuração padrão
    default_model: "claude-3-5-sonnet-20241022"
    temperature: 0.3
    max_tokens: 4000
    
    # Configurações específicas por stage (consolidadas de múltiplos arquivos)
    stage_configurations:
      political_analysis:
        model: "claude-3-5-haiku-20241022"
        temperature: 0.1
        max_tokens: 3000
        batch_size: 100
        
      sentiment_analysis:
        model: "claude-3-5-sonnet-20241022"
        temperature: 0.2
        max_tokens: 2200
        batch_size: 15
        
      network_analysis:
        model: "claude-sonnet-4-20250514"
        temperature: 0.3
        max_tokens: 3500
        batch_size: 10
        
      topic_interpretation:
        model: "claude-sonnet-4-20250514"
        temperature: 0.4
        max_tokens: 4000
        batch_size: 8
    
    # Configurações de API
    api_settings:
      rate_limits:
        requests_per_minute: 50
        tokens_per_minute: 50000
        max_retries: 3
        backoff_factor: 2.0
      
      # Estratégias de fallback
      fallback_models:
        "claude-sonnet-4-20250514": "claude-3-5-sonnet-20241022"
        "claude-3-5-sonnet-20241022": "claude-3-5-haiku-20241022"
        
  # Voyage.ai Configuration  
  voyage:
    default_model: "voyage-3.5-lite"
    dimensions: 1024
    max_tokens: 32000
    batch_size: 128
    
    # Configurações de cache
    cache_settings:
      enabled: true
      directory: "cache/embeddings"
      expiry_days: 30
      compression: true

# =============================================================================
# PROCESSAMENTO - CONFIGURAÇÃO UNIFICADA
# =============================================================================
processing:
  # Gestão de memória
  memory_management:
    target_usage_gb: 4.0
    max_usage_gb: 8.0
    adaptive_management: true
    cleanup_frequency: "after_each_stage"
    
  # Configurações de performance
  performance:
    enable_parallel_processing: true
    max_workers: 4
    chunk_size: 100
    enable_optimization_layers: true
    
  # Configurações de dados
  data_processing:
    delimiter: ";"
    encoding: "utf-8"
    handle_missing_values: true
    enable_data_validation: true

# =============================================================================
# MONITORAMENTO E CUSTOS
# =============================================================================
monitoring:
  # Monitoramento de custos
  cost_management:
    monthly_budget_limit: 200.0
    enable_alerts: true
    alert_threshold: 0.8
    
    # Custos por modelo (USD por 1K tokens)
    token_costs:
      "claude-3-5-haiku-20241022": 0.00025
      "claude-3-5-sonnet-20241022": 0.003
      "claude-sonnet-4-20250514": 0.015
      "voyage-3.5-lite": 0.00002
      
  # Monitoramento de performance
  performance_monitoring:
    enable_timing: true
    enable_memory_tracking: true
    enable_quality_metrics: true
    
# =============================================================================
# CONFIGURAÇÕES DE QUALIDADE
# =============================================================================
quality:
  # Validações
  validation:
    enable_input_validation: true
    enable_output_validation: true
    minimum_confidence_threshold: 0.7
    
  # Configurações de backup
  backup:
    enable_automatic_backup: true
    backup_frequency: "after_major_stages"
    retention_days: 30