# Configurações de Logging

# Configurações Gerais
version: "5.0.0"
disable_existing_loggers: false

# Formatadores
formatters:
  standard:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
    date_format: "%Y-%m-%d %H:%M:%S"
  
  detailed:
    format: "%(asctime)s [%(levelname)s] %(name)s (%(filename)s:%(lineno)d): %(message)s"
    date_format: "%Y-%m-%d %H:%M:%S"
  
  simple:
    format: "%(levelname)s: %(message)s"

# Handlers
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
  
  file_main:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/main/main.log
    max_bytes: 10485760  # 10MB
    backup_count: 5
    encoding: utf8
  
  file_pipeline:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/pipeline/pipeline.log
    max_bytes: 10485760  # 10MB
    backup_count: 10
    encoding: utf8
  
  file_utils:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: logs/utils/utils.log
    max_bytes: 5242880  # 5MB
    backup_count: 3
    encoding: utf8
    
  file_anthropic:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/anthropic/anthropic.log
    max_bytes: 10485760  # 10MB
    backup_count: 5
    encoding: utf8
    
  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/errors.log
    max_bytes: 10485760  # 10MB
    backup_count: 10
    encoding: utf8

# Loggers
loggers:
  # Logger principal da aplicação
  monitor_discurso_digital:
    level: INFO
    handlers: [console, file_main]
    propagate: false
  
  # Loggers por componente
  monitor_discurso_digital.pipeline:
    level: DEBUG
    handlers: [console, file_pipeline]
    propagate: false
  
  monitor_discurso_digital.utils:
    level: INFO
    handlers: [console, file_utils]
    propagate: false
  
  monitor_discurso_digital.anthropic:
    level: DEBUG
    handlers: [console, file_anthropic]
    propagate: false
  
  # Logger para erros de todas as fontes
  monitor_discurso_digital.errors:
    level: ERROR
    handlers: [console, error_file]
    propagate: false

# Logger raiz (captura tudo que não é especificado acima)
root:
  level: WARNING
  handlers: [console, error_file]
  propagate: true
