# ================================================================================
# CONFIGURAÇÃO MASTER - MONITOR DO DISCURSO DIGITAL v5.0.0
# ================================================================================
# 
# Este arquivo centraliza e organiza todas as configurações do projeto
# com hierarquia clara e estrutura modular para facilitar manutenção.
#
# Criado pela auditoria v5.0.0 - TASK-021
# Consolida: settings.yaml, logging.yaml, timeout_management.yaml, etc.
# ================================================================================

# =============================================================================
# METADADOS E VERSIONING
# =============================================================================
project:
  name: monitor-discurso-digital
  version: "5.0.0"
  description: "Monitor do Discurso Digital - Análise de Discurso Político Brasileiro: Polarização, Negacionismo e Autoritarismo"
  created_date: "2025-06-14"
  model_config_version: "5.0.0"
  audit_task: "TASK-021"
  
  # Responsável
  author: "Pablo Emanuel Romero Almada, Ph.D."
  institution: "Projeto de Pesquisa Acadêmica"
  
  # Pipeline status
  pipeline_stages: 22
  optimization_weeks: 5
  production_ready: true

# =============================================================================
# INCLUDES - ARQUIVOS DE CONFIGURAÇÃO ESPECÍFICOS
# =============================================================================
includes:
  # Configurações específicas por componente
  anthropic_models: "anthropic_models.yaml"
  voyage_embeddings: "voyage_embeddings.yaml"
  brazilian_political_lexicon: "brazilian_political_lexicon.yaml"
  
  # Configurações operacionais
  logging: "logging.yaml"
  timeout_management: "timeout_management.yaml"
  processing: "processing.yaml"
  
  # Nota: Arquivos inclusos devem existir para funcionalidade completa
  # Se ausentes, usar configurações default definidas abaixo

# =============================================================================
# CONFIGURAÇÕES PRINCIPAIS - HIERARCHICAL STRUCTURE
# =============================================================================

# -----------------------------------------------------------------------------
# 1. MODELOS E APIs
# -----------------------------------------------------------------------------
models:
  # Anthropic Configuration
  anthropic:
    default_model: "claude-3-5-sonnet-20241022"
    enhanced_model: "claude-sonnet-4-20250514"
    fast_model: "claude-3-5-haiku-20241022"
    
    # Configurações por stage (overrides)
    stage_specific:
      political_analysis: "claude-3-5-sonnet-20241022"
      topic_interpretation: "claude-sonnet-4-20250514"
      sentiment_analysis: "claude-3-5-haiku-20241022"
      network_analysis: "claude-3-5-haiku-20241022"
      qualitative_analysis: "claude-3-5-sonnet-20241022"
    
    # Rate limits e configurações de API
    rate_limits:
      requests_per_minute: 50
      tokens_per_minute: 50000
      max_retries: 3
      backoff_factor: 2.0
  
  # Voyage.ai Configuration
  voyage:
    default_model: "voyage-3.5-lite"
    dimensions: 1024
    max_tokens: 32000
    batch_size: 128
    
    # Cache settings
    cache_enabled: true
    cache_directory: "cache/embeddings"
    cache_expiry_days: 30

# -----------------------------------------------------------------------------
# 2. PROCESSAMENTO E PERFORMANCE
# -----------------------------------------------------------------------------
processing:
  # Memory management
  memory:
    target_usage_gb: 4.0
    max_usage_gb: 8.0
    garbage_collection_frequency: "after_each_stage"
    explicit_cleanup: true
  
  # Chunk processing
  chunking:
    default_chunk_size: 50000
    min_chunk_size: 10000
    max_chunk_size: 100000
    adaptive_sizing: true
    optimization_formula: "min(max_chunk, max(min_chunk, file_size // 100))"
  
  # I/O optimization
  io:
    compression_threshold_records: 100000
    compression_method: "gzip"
    csv_separator: ";"
    encoding: "utf-8"
    quoting_style: 1  # QUOTE_ALL
  
  # Parallel processing
  parallelization:
    max_workers: 5
    thread_pool_executor: true
    batch_processing: true
    concurrent_api_calls: 3

# -----------------------------------------------------------------------------
# 3. CUSTOS E LIMITES
# -----------------------------------------------------------------------------
cost_management:
  # Daily limits
  limits:
    daily_limit_usd: 50.0
    hourly_limit_usd: 10.0
    single_request_limit_usd: 5.0
    
  # Thresholds para alertas
  thresholds:
    warning_percentage: 80.0
    auto_downgrade_percentage: 90.0
    critical_percentage: 95.0
  
  # Monitoring
  monitoring:
    track_costs: true
    cost_alerts: true
    auto_model_downgrade: true
    cost_log_file: "logs/costs.json"

# -----------------------------------------------------------------------------
# 4. QUALIDADE E VALIDAÇÃO
# -----------------------------------------------------------------------------
quality:
  # Validation settings
  validation:
    enable_data_validation: true
    enable_schema_validation: true
    enable_quality_checks: true
    min_confidence_threshold: 0.7
  
  # Performance profiles
  profiles:
    research:
      min_confidence: 0.8
      enable_validation: true
      preferred_model_tier: "enhanced"
    
    production:
      min_confidence: 0.7
      enable_validation: false
      preferred_model_tier: "default"
    
    development:
      min_confidence: 0.6
      enable_validation: false
      preferred_model_tier: "fast"

# -----------------------------------------------------------------------------
# 5. CAMINHOS E DIRETÓRIOS
# -----------------------------------------------------------------------------
paths:
  # Diretórios principais
  base:
    project_root: "."
    data: "data"
    config: "config"
    logs: "logs"
    cache: "cache"
    results: "results"
    
  # Subdiretórios de dados
  data_subdirs:
    raw: "data/raw"
    interim: "data/interim"
    processed: "data/processed"
    uploads: "data/uploads"
    backups: "data/backups"
    
  # Subdiretórios de logs
  log_subdirs:
    main: "logs/main"
    pipeline: "logs/pipeline"
    anthropic: "logs/anthropic"
    errors: "logs/errors"
    costs: "logs/costs"
    
  # Cache directories
  cache_subdirs:
    embeddings: "cache/embeddings"
    unified_embeddings: "cache/unified_embeddings"
    claude_cache: "cache/claude"
    hybrid_search: "cache/hybrid_search"

# -----------------------------------------------------------------------------
# 6. CONFIGURAÇÕES DE ANÁLISE
# -----------------------------------------------------------------------------
analysis:
  # Political analysis
  political:
    confidence_threshold: 0.8
    conspiracy_detection: true
    negacionism_detection: true
    use_anthropic_classification: true
    hierarchical_levels: 4
    
  # Sentiment analysis
  sentiment:
    model_type: "anthropic"
    batch_size: 100
    confidence_threshold: 0.7
    enable_emotion_detection: true
    
  # Topic modeling
  topic_modeling:
    n_topics: 15
    alpha: 0.01
    beta: 0.01
    iterations: 1000
    use_anthropic_interpretation: true
    
  # Network analysis
  network:
    max_nodes: 500
    min_edge_weight: 3
    community_sample_size: 100
    use_anthropic: true
    
  # Clustering
  clustering:
    algorithm: "kmeans"
    n_clusters: 10
    use_voyage_embeddings: true
    semantic_similarity_threshold: 0.7

# -----------------------------------------------------------------------------
# 7. TIMEOUT E RECUPERAÇÃO
# -----------------------------------------------------------------------------
timeouts:
  # Global timeouts (segundos)
  global:
    default: 1800  # 30 minutos
    max_timeout: 3600  # 1 hora
    
  # Stage-specific timeouts
  stages:
    "01_chunking": 300
    "02_encoding_validation": 600
    "03_deduplication": 900
    "05_political_analysis": 1800
    "08_sentiment_analysis": 1200
    "09_topic_modeling": 1500
    "11_clustering": 1800
    "15_network_analysis": 1200
    "18_topic_interpretation": 2400
    
  # Recovery settings
  recovery:
    max_retries: 3
    exponential_backoff: true
    base_delay: 5
    max_delay: 300

# -----------------------------------------------------------------------------
# 8. FEATURES E TOGGLES
# -----------------------------------------------------------------------------
features:
  # Pipeline features
  pipeline:
    enable_checkpoints: true
    enable_backup: true
    auto_cleanup_backups: true
    backup_retention_days: 7
    
  # Performance features
  performance:
    enable_caching: true
    enable_compression: true
    enable_parallel_processing: true
    enable_memory_optimization: true
    
  # Analysis features
  analysis_features:
    enable_anthropic_api: true
    enable_voyage_api: true
    enable_spacy_processing: true
    enable_semantic_search: true
    
  # Dashboard features
  dashboard:
    enable_realtime_monitoring: true
    enable_cost_tracking: true
    enable_quality_charts: true
    auto_refresh_interval: 30

# =============================================================================
# CONFIGURAÇÕES ESPECÍFICAS POR AMBIENTE
# =============================================================================
environments:
  # Development environment
  development:
    cost_limits:
      daily_limit_usd: 10.0
      hourly_limit_usd: 2.0
    models:
      default_anthropic: "claude-3-5-haiku-20241022"
    processing:
      chunk_size: 10000
    
  # Production environment  
  production:
    cost_limits:
      daily_limit_usd: 100.0
      hourly_limit_usd: 20.0
    models:
      default_anthropic: "claude-3-5-sonnet-20241022"
    processing:
      chunk_size: 50000
      
  # Research environment
  research:
    cost_limits:
      daily_limit_usd: 200.0
      hourly_limit_usd: 50.0
    models:
      default_anthropic: "claude-sonnet-4-20250514"
    processing:
      chunk_size: 100000

# =============================================================================
# CONFIGURAÇÕES DE MIGRAÇÃO E COMPATIBILIDADE
# =============================================================================
migration:
  # Configurações para compatibilidade com versões anteriores
  legacy_support:
    support_v4_configs: true
    auto_convert_formats: true
    backup_before_migration: true
    
  # Mapeamento de configurações antigas
  config_mapping:
    "model": "models.anthropic.default_model"
    "chunk_size": "processing.chunking.default_chunk_size"
    "timeout": "timeouts.global.default"

# =============================================================================
# VALIDAÇÃO E SCHEMAS
# =============================================================================
validation:
  # Schema validation
  schemas:
    validate_on_load: true
    strict_mode: false
    allow_additional_properties: true
    
  # Required fields validation
  required_sections:
    - "project"
    - "models"
    - "processing"
    - "paths"
    
  # Automatic validation rules
  rules:
    version_format: "semantic_version"  # X.Y.Z
    cost_limits_positive: true
    timeout_values_positive: true
    path_existence_check: false  # Set to true for strict validation

# =============================================================================
# DOCUMENTAÇÃO E METADADOS
# =============================================================================
documentation:
  config_description: |
    Arquivo master de configuração para o Monitor do Discurso Digital v5.0.0.
    
    Este arquivo implementa uma estrutura hierárquica que centraliza todas
    as configurações do projeto, eliminando duplicações e facilitando
    manutenção.
    
    Principais benefícios:
    - Configuração única e centralizada
    - Hierarquia clara e organizada
    - Suporte a múltiplos ambientes
    - Validação automática
    - Compatibilidade com versões anteriores
    
  usage_examples:
    - "Para desenvolvimento: use environment=development"
    - "Para produção: use environment=production" 
    - "Para pesquisa: use environment=research"
    
  changelog:
    "5.0.0": "Criação do arquivo master com hierarquia completa"
    "4.9.9": "Configurações dispersas em múltiplos arquivos"