# Network Configuration - TASK-023 v5.0.0
# Consolidates hardcoded network settings from dashboard and services
# Enables easy configuration for different environments

network:
  # Dashboard configurations
  dashboard:
    main:
      host: "localhost"
      port: 8501
      address: "localhost"
      headless: true
      browser_stats: false
      telemetry_optout: true
      
    data_analysis:
      host: "localhost" 
      port: 8503
      address: "localhost"
      
    # Theme configuration
    theme:
      primary_color: "#1f77b4"
      background_color: "#ffffff"
      secondary_background_color: "#f0f2f6"
      text_color: "#262730"
      
  # API endpoints (if external APIs are used)
  apis:
    anthropic:
      base_url: "https://api.anthropic.com"
      timeout: 30
      max_connections: 10
      
    voyage:
      base_url: "https://api.voyageai.com"
      timeout: 30
      max_connections: 10
      
  # Development settings
  development:
    auto_reload: true
    debug_mode: false
    cors_enabled: true
    allowed_origins:
      - "http://localhost:8501"
      - "http://localhost:8503"
      - "http://127.0.0.1:8501"
      - "http://127.0.0.1:8503"
      
  # Production settings
  production:
    auto_reload: false
    debug_mode: false
    cors_enabled: false
    ssl_enabled: false
    max_upload_size_mb: 200
    
    # Security headers
    security:
      enable_https_redirect: false
      enable_hsts: false
      enable_csrf_protection: true
      
  # Connection pooling
  connection_pool:
    max_size: 20
    max_overflow: 10
    timeout: 30
    recycle: 3600

# Circuit Breaker Configuration (Fase 3 do Plano de Aprimoramento)
circuit_breaker:
  anthropic:
    failure_threshold: 5
    recovery_timeout: 60.0
    success_threshold: 3
    call_timeout: 30.0
    
  voyage:
    failure_threshold: 3
    recovery_timeout: 45.0
    success_threshold: 2
    call_timeout: 25.0
    
  default:
    failure_threshold: 4
    recovery_timeout: 50.0
    success_threshold: 2
    call_timeout: 20.0