# Paths Configuration - TASK-023 v5.0.0
# Consolidates hardcoded file paths and directory structures
# Centralizes all path configuration for better maintainability and environment flexibility

paths:
  # Data directories
  data:
    # Input data
    uploads: "data/uploads"
    datasets_full: "data/DATASETS_FULL"
    samples: "data/samples"
    
    # Processing data
    interim: "data/interim" 
    processed: "data/processed"
    raw: "data/raw"
    
    # Output data
    output: "pipeline_outputs"
    results: "results"
    exports: "exports"
    
    # Cache directories
    cache:
      root: "cache"
      embeddings: "cache/embeddings"
      responses: "cache/responses"
      unified_embeddings: "cache/unified_embeddings"
      l2_disk: "cache/unified_embeddings/l2_disk"
    
  # Logs and monitoring
  logs:
    root: "logs"
    pipeline: "logs/pipeline_execution.log"
    errors: "logs/errors.log"
    performance: "logs/performance.log"
    api_calls: "logs/api_calls.log"
    
    # Timestamped logs
    pipeline_timestamped: "logs/pipeline/pipeline_{timestamp}.log"
    validation_reports: "logs/pipeline/validation_report_{timestamp}.json"
    
  # Backup directories
  backup:
    root: "backups"
    text_cleaning: "data/interim/text_cleaning_backup_{timestamp}.csv"
    enhanced_cleaning: "data/interim/enhanced_cleaning_backup_{timestamp}.csv"
    pipeline_state: "backups/pipeline_checkpoint_{timestamp}.json"
    configurations: "backups/config_backup_{timestamp}"
    
  # Dashboard and UI
  dashboard:
    root: "src/dashboard"
    data: "src/dashboard/data"
    uploads: "src/dashboard/data/uploads"
    results: "src/dashboard/data/dashboard_results"
    temp: "src/dashboard/temp"
    static: "src/dashboard/static"
    templates: "src/dashboard/templates"
    
  # Configuration files
  config:
    root: "config"
    settings: "config/settings.yaml"
    anthropic: "config/anthropic.yaml"
    processing: "config/processing.yaml"
    voyage_embeddings: "config/voyage_embeddings.yaml"
    timeout_management: "config/timeout_management.yaml"
    api_limits: "config/api_limits.yaml"
    network: "config/network.yaml"
    paths: "config/paths.yaml"
    
  # Temporary files
  temp:
    root: "temp"
    processing: "temp/processing"
    uploads: "temp/uploads"
    cache: "temp/cache"
    benchmark: "/tmp/benchmark_test"
    
  # Output file patterns
  patterns:
    # Pipeline stage outputs
    stage_output: "sample_dataset_v495_{stage:02d}_{stage_name}.csv"
    compressed_output: "sample_dataset_v495_{stage:02d}_{stage_name}.csv.{compression}"
    
    # Statistics and reports
    pre_stats: "{stage:02d}b_pre_{stage_name}_stats.json"
    post_stats: "{stage:02d}b_post_{stage_name}_stats.json"
    
    # Backups with timestamps
    timestamped_backup: "{base_name}_backup_{timestamp}.{extension}"
    
  # Environment-specific paths
  environments:
    development:
      data_root: "data"
      cache_root: "cache"
      logs_root: "logs"
      
    testing:
      data_root: "test_data"
      cache_root: "test_cache"
      logs_root: "test_logs"
      
    production:
      data_root: "/var/lib/monitor-discurso-digital/data"
      cache_root: "/var/cache/monitor-discurso-digital"
      logs_root: "/var/log/monitor-discurso-digital"
      
  # Path utilities
  utilities:
    # Ensure these directories exist on startup
    auto_create:
      - "data/uploads"
      - "data/interim"
      - "data/processed"
      - "logs"
      - "cache/embeddings"
      - "pipeline_outputs"
      - "src/dashboard/data/uploads"
      - "src/dashboard/data/dashboard_results"
      - "temp"
      
    # Clean these directories on cleanup
    auto_cleanup:
      - "temp/*"
      - "cache/responses/*"
      - "logs/*.log.old"
      
  # File extensions and formats
  formats:
    data:
      csv: ".csv"
      json: ".json"
      yaml: ".yaml"
      pkl: ".pkl"
      
    compression:
      gzip: ".gz"
      lz4: ".lz4"
      zstd: ".zst"
      
    logs:
      log: ".log"
      error: ".error"
      debug: ".debug"