# Enhanced Model Configuration
enhanced_model_config:
  info: Stage-specific model configurations consolidated in anthropic.stage_specific_configs
  priority: stage_specific_configs > anthropic defaults > environment variables
  supported_stages:
  - political_analysis (stage_05_political)
  - sentiment_analysis (stage_08_sentiment) 
  - network_analysis (stage_15_network)
  - qualitative_analysis (stage_16_qualitative)
  - pipeline_review (stage_17_review)
  - topic_interpretation (stage_18_topics)
  - validation (stage_20_validation)

anthropic:
  cost_monitoring: true
  enhanced_config_enabled: true
  fallback_enabled: true
  max_tokens: 4000
  model: claude-3-5-sonnet-20241022
  temperature: 0.3
  
  # 🎯 STAGE-SPECIFIC CONFIGURATIONS (CONSOLIDATED)
  stage_specific_configs:
    stage_05_political:
      model: "claude-3-5-haiku-20241022"
      temperature: 0.1
      max_tokens: 3000
      batch_size: 100
      justification: "Hierarchical political classification 4 levels precision"
      
    stage_08_sentiment:
      model: "claude-3-5-sonnet-20241022"
      temperature: 0.2
      max_tokens: 2200
      batch_size: 20
      justification: "Contextual sentiment analysis with political nuances"
      
    stage_15_network:
      model: "claude-sonnet-4-20250514"
      temperature: 0.3
      max_tokens: 3500
      batch_size: 15
      justification: "Complex network analysis requires latest model"
      
    stage_16_qualitative:
      model: "claude-3-5-sonnet-20241022"
      temperature: 0.15
      max_tokens: 3000
      batch_size: 25
      justification: "Qualitative analysis requires precision and consistency"
      
    stage_17_review:
      model: "claude-3-5-sonnet-20241022"
      temperature: 0.25
      max_tokens: 2800
      batch_size: 10
      justification: "Pipeline review requires balanced creativity"
      
    stage_18_topics:
      model: "claude-sonnet-4-20250514"
      temperature: 0.4
      max_tokens: 4000
      batch_size: 8
      justification: "Topic interpretation benefits from latest model capabilities"
      
    stage_20_validation:
      model: "claude-3-5-haiku-20241022"
      temperature: 0.1
      max_tokens: 2200
      batch_size: 50
      justification: "Validation requires speed and consistency"

# Cost monitoring and optimization
cost_monitoring:
  enabled: true
  alert_threshold_usd: 50.0
  daily_limit_usd: 100.0
  cost_per_1k_tokens:
    claude-3-5-sonnet-20241022: 0.003
    claude-3-5-haiku-20241022: 0.00025
    claude-sonnet-4-20250514: 0.015
  
# Voyage.ai embeddings configuration
voyage:
  model: voyage-3.5-lite
  batch_size: 128
  enable_caching: true
  cache_ttl_hours: 168
  cost_optimization_enabled: true
  max_messages_per_dataset: 50000
  
  # Performance settings
  performance:
    parallel_workers: 4
    max_retries: 3
    timeout_seconds: 30
    rate_limit_per_minute: 300

# Project metadata
project:
  name: digital-discourse-monitor
  description: 'Digital Discourse Monitor - Brazilian Political Discourse Analysis: 
    Polarization, Denialism and Authoritarianism'
  model_config_version: 5.0.0
  version: 5.0.0

# Processing configuration
processing:
  chunk_size: 10000
  memory_limit: 4GB
  enable_parallelization: true
  max_workers: 4
  
  # Quality control
  quality_control:
    min_text_length: 10
    max_text_length: 10000
    min_confidence_threshold: 0.7
    enable_validation: true

# Cache configuration
cache:
  enabled: true
  memory_limit_mb: 1024
  disk_limit_gb: 10
  ttl_hours: 24
  compression_enabled: true
  
# Logging configuration
logging:
  level: INFO
  enable_file_logging: true
  log_rotation: true
  max_log_size_mb: 100
  backup_count: 5
  
  # Logger hierarchy
  loggers:
    digital_discourse_monitor:
      level: INFO
    digital_discourse_monitor.pipeline:
      level: INFO
    digital_discourse_monitor.anthropic:
      level: WARNING
    digital_discourse_monitor.voyage:
      level: INFO

# Performance optimization
optimization:
  enable_memory_optimization: true
  enable_io_optimization: true
  enable_regex_precompilation: true
  adaptive_chunking: true
  
  # Memory management
  memory_management:
    target_limit_gb: 4.0
    gc_threshold: 0.8
    enable_explicit_cleanup: true
    
# Data paths configuration
paths:
  data_root: "data"
  raw_data: "data/raw"
  interim_data: "data/interim"
  processed_data: "data/processed"
  cache_root: "cache"
  logs_root: "logs"
  config_root: "config"

# Security settings
security:
  enable_api_key_validation: true
  mask_sensitive_logs: true
  secure_temp_files: true